  spring:
    application:
      name: gateway
    cloud:
      gateway:
        mvc:
          routes:
            - id: example-route
              filters:
                - RewritePath=/api/?(?<segment>.*), /$\{segment}
              uri: lb://resource-server
              predicates:
                - Path=/api/**
